DROP TABLE IF EXISTS ZEPTO;

CREATE TABLE IF NOT EXISTS ZEPTO (
	"SKU_ID" SERIAL PRIMARY KEY,
	"CATEGORY" VARCHAR(120),
	"NAME" VARCHAR(150) NOT NULL,
	"MRP" NUMERIC(8,2),
	"DISCOUNTPERCENT" NUMERIC(5,2),
	"AVAILABLEQUANTITY" INTEGER,
	"DISCOUNTEDSELLINGPRICE" NUMERIC(8,2),
	"weightInGms" INTEGER,
	"OUTOFSTOCK" BOOLEAN,
	"QUANTITY" INTEGER
);

-- JB BHI AP APNE DATA KO IMPORT KRE HO TO APKO EXCEL FILE KO SAVE AS KRNA HAI CSV UTF-8 (COMMA DELIMINTED) ALSO SKU_ID HUMNE CREATE KI HAI TO JN=B IMPORT KRE HO TO YAD RKHNA COLUMN M JAKR USAKO HATA DENA 

-- DATA EXPLORATIONN

-- COUNT ALL ROWS

SELECT COUNT (*) 
FROM ZEPTO;

-- SAMPLE DATA

SELECT * FROM ZEPTO
LIMIT 10;

-- CHECK IF THERE IS ANY NULL VALUE

SELECT * FROM ZEPTO
WHERE "NAME" IS NULL
OR 
"CATEGORY" IS NULL
OR
"MRP" IS NULL 
OR
"DISCOUNTPERCENT" IS NULL 
OR
"AVAILABLEQUANTITY" IS NULL
OR 
"DISCOUNTEDSELLINGPRICE" IS NULL
OR
"weightInGms" IS NULL
OR
"OUTOFSTOCK" IS NULL
OR
"QUANTITY" IS NULL;

-- COLUMN NAME JB BHI LIKHO DOUBLE INVERTED M LIKHO 

-- DIFFERENT PRODUCT CATEGORY 

SELECT "CATEGORY"
FROM ZEPTO
GROUP BY "CATEGORY"
ORDER BY "CATEGORY";

-- PRODUCTS IN STOCK VS OUT OF STOCK 

SELECT COUNT("OUTOFSTOCK")
FROM ZEPTO
WHERE "OUTOFSTOCK" = 'TRUE'
GROUP BY "OUTOFSTOCK";

SELECT COUNT("OUTOFSTOCK")
FROM ZEPTO
WHERE "OUTOFSTOCK" = 'FALSE'
GROUP BY "OUTOFSTOCK";

-- OR AGR EK HI SAB SHOW KRNA HAI TO HUM COUNT KREGE OUTOFSTOCK VALE COLUMN KO OR USKO GROUP BY KR DENGE KI FALLSE KA KITNA COUNT HAI OR TRUE KA KITNA COUNT HAI 

SELECT COUNT("OUTOFSTOCK"), "OUTOFSTOCK"
FROM ZEPTO
GROUP BY "OUTOFSTOCK";

SELECT "OUTOFSTOCK", COUNT("OUTOFSTOCK")
FROM ZEPTO
GROUP BY "OUTOFSTOCK";

-- COUNT BAD M CHAIYE TO BAD M LIKHO PEHEL CHAIYE TO PEHLE LIKHO 
-- BY THIS QUERY WE KNOW KI FACTORY KI M STOCK KITNA HAI OR KITNA NAHI HAI 

-- PRODUCT NAMES PRESENT MULTIPLE TIMES

SELECT "NAME", COUNT("NAME") AS NO_OF_UNITS
FROM ZEPTO
GROUP BY "NAME"
ORDER BY NO_OF_UNITS DESC;
-- BASICALLY YE HUMKO COUNT OF PRODUCT DE RAHA HAI KI YE PRODUCT HAMARE LIST M KITNE BAR AVAILABLE HAI 
-- HAVING COUNT > 1 OPTIONAL HAI LIKHNA

-- DATA CLEANING

-- WE WILL SEE IF ANY PRODUCT WITH PRICE = 0 

SELECT * 
FROM ZEPTO
WHERE "MRP" = 0
OR
"DISCOUNTEDSELLINGPRICE" = 0;

-- MAY BE YE JO HUA HUMARA SE GALAT DATA ENTRY HUI HO TO HUMKO AB IS ROW KO DELETE KRNA HAI TO 

DELETE FROM ZEPTO
WHERE "MRP" = 0
OR
"DISCOUNTEDSELLINGPRICE" = 0;

--CONVERT PAISE INTO RUPEES
UPDATE ZEPTO
SET "MRP" = "MRP"/100.00,
"DISCOUNTEDSELLINGPRICE" = "DISCOUNTEDSELLINGPRICE"/100.00;

SELECT "MRP", "DISCOUNTEDSELLINGPRICE"
FROM ZEPTO

-- NOW WILL FIND SOME BUSINESS INSIGHTS

--Q1-- TOP 10 BEST VALUED PRODUCTS BASED ON THE DISCOUNT PERCENTAGE.

SELECT "NAME", "DISCOUNTPERCENT", "MRP"
FROM ZEPTO
ORDER BY "DISCOUNTPERCENT" DESC
LIMIT 10;
-- THIS IS USED FOR BOTH CUSTOMERS FOR BARGIN AND FOR COMPANY THAT WHICH PRODUCT IS HEAVILY PROMOTED

--Q2-- WHAT ARE THE PRODUCT WITH HIGH MRP BUT OUT OF STOCK

SELECT "NAME", "MRP", "OUTOFSTOCK"
FROM ZEPTO
WHERE "OUTOFSTOCK" = 'TRUE'
ORDER BY "MRP" DESC;
-- BASICALLY ISE HUME YE PATA CHLRA KI AISE KONSA PRODUCT HAI KI PRICE BHUT JADA HAI OR SATH KI OUT OF STOCK 
-- MTLB JADA PRICE HONE KE BAD BHI YE PRODUCT KI SALE ACHI AHI 
-- AGR M SELCT DISTINCT KRTI HU TO NAME REPEAT NAHI HOGA
-- ISLIE JITNA JLDI HO SKE COMPANY KO RESTOCK KRNA CHAIYE 


SELECT DISTINCT "NAME", "MRP", "OUTOFSTOCK"
FROM ZEPTO
WHERE "OUTOFSTOCK" = 'TRUE'
ORDER BY "MRP" DESC;

--Q3--CALCULATE REVENUE FOR EACH CATEGORY
SELECT "CATEGORY", SUM("DISCOUNTEDSELLINGPRICE") AS TOTAL_REVENUE
FROM ZEPTO
GROUP BY "CATEGORY"
ORDER BY TOTAL_REVENUE DESC;
-- ISSE PATA CHLRA HAI KI KONSI CATEGORY SBSE JADA HIGH REVENUE GENERATE KRKE DE RHI HAI 

--Q4-- ALL PRODUCT WHERE MRP IS HICH >500 BUT DISCOUNT IS LESS THAN 10%

SELECT "NAME", "MRP", "DISCOUNTPERCENT"
FROM ZEPTO
WHERE "MRP" >= 500
AND "DISCOUNTPERCENT" < 10
ORDER BY "MRP" DESC, "DISCOUNTPERCENT" DESC;
-- THIS ITEM ARE POPULAR ENOUGH AND SELL WITHOUT ANY DISCOUNTS

SELECT "NAME", "MRP", "DISCOUNTPERCENT"
FROM ZEPTO
ORDER BY "MRP" DESC, "DISCOUNTPERCENT" DESC;
-- YE UPR VALI QUERY BASE HAI 

--Q5-- WHICH PRODUCT CATEGORY OFFERING THE HIGHEST AVERAGE DISCOUNTPERCENTAGE

SELECT "CATEGORY", AVG("DISCOUNTPERCENT") AS AVG_DISCOUNT
FROM ZEPTO
GROUP BY "CATEGORY"
ORDER BY AVG_DISCOUNT DESC
-- BASICALLY CATEGORYWISE AVG DISCOUNT PERCENT NIKALE HAHI 
--AVG YA KOI BHI AGGREGATE FUNCTION LAGAN REHTA HAI QKI GROUP BY OR ORDER BY DONO HI USE HUA HAI 
-- BASICALLY USE BY MARKETING TEAMS TO KNOW WHERE PRICE CUTS ARE HAPPEING THE MOST AND HOW THEY CAN OPTIMISE THEM

--Q6--FINDING PRICE PER GRM FOR PRODICTS ABOVE 100G AND SORT BY BEST VALUES

SELECT DISTINCT
	"NAME",
	"weightInGms",
	"DISCOUNTEDSELLINGPRICE",
ROUND("DISCOUNTEDSELLINGPRICE" / "weightInGms", 2) AS PRICE_PER_GMS
FROM ZEPTO
WHERE "weightInGms" >100
ORDER BY PRICE_PER_GMS;

--Q7-- GROUP PRODUCTS PRODUCTS INTO CATEOGRIES LIKE LOW, MEDIUM, BULK
SELECT DISTINCT "NAME", "weightInGms",
	CASE
	    WHEN "weightInGms" < 1000 THEN 'Low'
		WHEN "weightInGms" < 5000 THEN 'Medium'
		WHEN "weightInGms" > 5000 THEN 'Bulk'
 	END AS weight_Category
FROM ZEPTO;
-- THIS KIND OF SEGMENTATION IS HELPFUL FOR PACKING DELIVERY PLANNING AND BULK ORDER STRAGIES

--Q8-- TOTAL INVENTORY WEIGHT PER CATEGORY

SELECT "CATEGORY", SUM("weightInGms" * "AVAILABLEQUANTITY") AS TOTAL_WEIGHT
FROM ZEPTO
GROUP BY "CATEGORY"
ORDER BY TOTAL_WEIGHT;
-- HELPS IN WAREHOUSE PLANNING AND IDENTIFY BULKY PRODUCT CATEGORY